package tm:plugin-system;

interface event-api {
	record before-send {
		content: option<string>,
		to: option<string>,
		fr-om: option<string>,
		subject: option<string>
	}
	record after-send {
		content: option<string>
	}
	record before-receive {
		content: option<string>
	}
	record after-receive {
		content: option<string>
	}


	// The event that is triggered by termail.
	// This is used as the single source of truth for the event. 
	// If you plan to extend the event system, you must also
	// extend the src/plugins/events.rs Hook enum and add the new event
	// to the variant.
	variant event {
		before-send(before-send),
		after-send(after-send),
		before-receive(before-receive),
		after-receive(after-receive),
	}
}
interface host-api {
	// The plugin calls this function to perform an action on the host.
	// The invocation-id must be valid and active.
	call-host: func(invocation-id: string, request: string) -> result<string, string>;
}

world plugin {
	import host-api;
	use event-api.{event};
	
	// termail will call this function when a specific event is triggered
	// on the host side that the plugin has registered for. This is used
	// to notify the plugin that an event has occurred.
	//
	// The plugin processes the event and returns the modified version.
	export notify: func(event: event) -> event;
}