package tm:plugin-system;

// // termail functins that plugins can call
interface termail-host {
	// termail will store the invocation-id and call
	invoke: func(invocation-id: string, event: string) -> string;
}

world plugin {
	import termail-host;

	// termail will call this function when a specific event is triggered
	// on the host side that the plugin has registered for. This is used 
	// to notify the plugin that an event has occurred.
	export on-notify: func(invocation-id: string, event: string) -> string;
}